In [56]:
# Load Data
import pandas as pd
df=pd.read_csv("ecommerce_data.csv")

# Inspect Data

In [25]:
df.tail()

,order_id,customer_id,city,product,category,price,quantity,order_date,payment_method
17,ORD-78437,C115,Kathmandu,Phone,Electronics,500,2,2024-02-10,Credit Card
18,ORD-78438,C116,Dharan,Oil,Groceries,10,6,2024-02-12,Cash
19,ORD-78439,C117,Pokhara,Jeans,Clothing,25,1,2024-02-15,eSewa
20,ORD-78440,C118,Hetauda,Soap,Personal Care,3,8,2024-02-18,Khalti
21,ORD-78440,C118,Hetauda,Soap,Personal Care,3,8,2024-02-18,Khalti

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        22 non-null     str
 1   customer_id     22 non-null     str
 2   city            22 non-null     str
 3   product         22 non-null     str
 4   category        22 non-null     str
 5   price           22 non-null     int64
 6   quantity        22 non-null     int64
 7   order_date      22 non-null     str
 8   payment_method  21 non-null     str
dtypes: int64(2), str(7)
memory usage: 1.7 KB

In [27]:
df.describe()

            price   quantity
count   22.000000  22.000000
mean   117.863636   3.454545
std    215.503242   2.595367
min      2.000000   1.000000
25%      8.000000   1.250000
50%     17.500000   3.000000
75%     70.000000   4.750000
max    800.000000  10.000000

# Clean Data

In [40]:
df.isnull().sum()

order_id          0
customer_id       0
city              0
product           0
category          0
price             0
quantity          0
order_date        0
payment_method    1
dtype: int64

In [41]:
df.dropna()

,order_id,customer_id,city,product,category,price,quantity,order_date,payment_method
0,ORD-78421,C101,Kathmandu,Laptop,Electronics,800,1,2024-01-05,Credit Card
1,ORD-78422,C102,Pokhara,Rice,Groceries,20,5,2024-01-06,Cash
2,ORD-78423,C103,Lalitpur,T-shirt,Clothing,15,3,2024-01-07,eSewa
3,ORD-78424,C104,Bhaktapur,Shampoo,Personal Care,8,2,2024-01-08,Khalti
4,ORD-78425,C105,Biratnagar,Phone,Electronics,500,1,2024-01-10,Credit Card
5,ORD-78426,C106,Butwal,Oil,Groceries,10,4,2024-01-12,Cash
6,ORD-78427,C101,Kathmandu,Jeans,Clothing,25,2,2024-01-15,eSewa
7,ORD-78428,C102,Lalitpur,Facewash,Personal Care,6,3,2024-01-18,Khalti
8,ORD-78429,C107,Bharatpur,Tablet,Electronics,300,1,2024-01-20,Credit Card
9,ORD-78430,C108,Dharan,Biscuits,Groceries,2,10,2024-01-22,Cash
10,ORD-78431,C109,Pokhara,Shoes,Clothing,40,1,2024-01-25,eSewa
12,ORD-78432,C110,Hetauda,Soap,Personal Care,3,5,2024-01-28,Khalti
13,ORD-78433,C111,Kathmandu,Monitor,Electronics,200,1,2024-02-01,Credit Card
14,ORD-78434,C112,Biratnagar,Rice,Groceries,20,3,2024-02-03,Cash
15,ORD-78435,C113,Butwal,T-shirt,Clothing,15,2,2024-02-05,eSewa
16,ORD-78436,C114,Bharatpur,Shampoo,Personal Care,8,4,2024-02-07,Khalti
17,ORD-78437,C115,Kathmandu,Phone,Electronics,500,2,2024-02-10,Credit Card
18,ORD-78438,C116,Dharan,Oil,Groceries,10,6,2024-02-12,Cash
19,ORD-78439,C117,Pokhara,Jeans,Clothing,25,1,2024-02-15,eSewa
20,ORD-78440,C118,Hetauda,Soap,Personal Care,3,8,2024-02-18,Khalti
21,ORD-78440,C118,Hetauda,Soap,Personal Care,3,8,2024-02-18,Khalti

In [15]:
df.drop_duplicates(inplace=True)
df.tail()

,order_id,customer_id,city,product,category,price,quantity,order_date,payment_method
15,ORD-78436,C114,Bharatpur,Shampoo,Personal Care,8,4,2024-02-07,Khalti
16,ORD-78437,C115,Kathmandu,Phone,Electronics,500,2,2024-02-10,Credit Card
17,ORD-78438,C116,Dharan,Oil,Groceries,10,6,2024-02-12,Cash
18,ORD-78439,C117,Pokhara,Jeans,Clothing,25,1,2024-02-15,eSewa
19,ORD-78440,C118,Hetauda,Soap,Personal Care,3,8,2024-02-18,Khalti

# Transform Data

In [57]:
# Total revenue per order
df["total_amount"]=df["price"]*df["quantity"]
pos=df.columns.get_loc("quantity")+1 # find index of quantity
df.insert(pos,"total_amount",df.pop("total_amount"))
df=df.set_index("order_id")
print(df.head())

          customer_id        city  product       category  price  quantity  \
order_id
ORD-78421        C101   Kathmandu   Laptop    Electronics    800         1
ORD-78422        C102     Pokhara     Rice      Groceries     20         5
ORD-78423        C103    Lalitpur  T-shirt       Clothing     15         3
ORD-78424        C104   Bhaktapur  Shampoo  Personal Care      8         2
ORD-78425        C105  Biratnagar    Phone    Electronics    500         1

           total_amount  order_date payment_method
order_id
ORD-78421           800  2024-01-05    Credit Card
ORD-78422           100  2024-01-06           Cash
ORD-78423            45  2024-01-07          eSewa
ORD-78424            16  2024-01-08         Khalti
ORD-78425           500  2024-01-10    Credit Card

In [47]:
# orderdate to datetime
df["order_date"]=pd.to_datetime(df["order_date"])
print(df.dtypes)

order_id                     str
customer_id                  str
city                         str
product                      str
category                     str
price                      int64
quantity                   int64
order_date        datetime64[us]
payment_method               str
total_revenue              int64
dtype: object

# Analyze Data

In [58]:
# Total Revenue
total_renvenue=df["total_amount"].sum()
print(f"Total Revenue: {total_renvenue}$")

Total Revenue: 3639$

In [63]:
# Most sold product
result=df.groupby("product")["quantity"].sum().sort_values(ascending=False).head(3) # top 3 product
print(f"Most sold Products: \n{result}")

Most sold Products:
product
Soap        21
Oil         10
Biscuits    10
Name: quantity, dtype: int64

# Group Data

In [65]:
# Revenue by Category
revenue_by_category=df.groupby("category")["total_amount"].sum()
print(revenue_by_category)

category
Clothing          430
Electronics      2800
Groceries         280
Personal Care     129
Name: total_amount, dtype: int64

In [ ]:
# Sales by City
sales_by_city=df.groupby("city")["total_amount"].sum()
print(sales_by_city)