In [19]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [25, 30, 35, 40]
})
df2 = pd.DataFrame({
    "id": [3, 4, 5, 6],
    "department": ["HR", "IT", "Finance", "Marketing"],
    "salary": [50000, 60000, 55000, 45000]
})

# Merge

In [4]:
# Merge df1 & df2 on id (default inner join)
pd.merge(df1,df2,on="id")

   id     name  age department  salary
0   3  Charlie   35         HR   50000
1   4    David   40         IT   60000

In [5]:
# Perform a left merge of df1 with df2 on id.
pd.merge(df1,df2,on="id",how="left")

   id     name  age department   salary
0   1    Alice   25        NaN      NaN
1   2      Bob   30        NaN      NaN
2   3  Charlie   35         HR  50000.0
3   4    David   40         IT  60000.0

In [ ]:
# Perform a right merge of df1 with df2 on id.
pd.merge(df1,df2,on="id",how="right_on=")

   id     name   age department  salary
0   3  Charlie  35.0         HR   50000
1   4    David  40.0         IT   60000
2   5      NaN   NaN    Finance   55000
3   6      NaN   NaN  Marketing   45000

# Concat

In [7]:
# Concatenate df1 & df2 vertically(stack rows).
pd.concat([df1,df2],axis=0)

   id     name   age department   salary
0   1    Alice  25.0        NaN      NaN
1   2      Bob  30.0        NaN      NaN
2   3  Charlie  35.0        NaN      NaN
3   4    David  40.0        NaN      NaN
0   3      NaN   NaN         HR  50000.0
1   4      NaN   NaN         IT  60000.0
2   5      NaN   NaN    Finance  55000.0
3   6      NaN   NaN  Marketing  45000.0

In [8]:
# Concatenate df1 & df2 horizontally.
pd.concat([df1,df2],axis=1)

   id     name  age  id department  salary
0   1    Alice   25   3         HR   50000
1   2      Bob   30   4         IT   60000
2   3  Charlie   35   5    Finance   55000
3   4    David   40   6  Marketing   45000

In [10]:
# Concatenate df1 twice and reset the index.
pd.concat([df1,df1],ignore_index=True)

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   1    Alice   25
5   2      Bob   30
6   3  Charlie   35
7   4    David   40

# Join

In [20]:
# Set id as index in both DF and join them.
df1=df1.set_index("id")
df2=df2.set_index("id")
df1.join(df2,how="outer")

       name   age department   salary
id
1     Alice  25.0        NaN      NaN
2       Bob  30.0        NaN      NaN
3   Charlie  35.0         HR  50000.0
4     David  40.0         IT  60000.0
5       NaN   NaN    Finance  55000.0
6       NaN   NaN  Marketing  45000.0

In [21]:
# Perform a left join.
df1.join(df2,how="left")

       name  age department   salary
id
1     Alice   25        NaN      NaN
2       Bob   30        NaN      NaN
3   Charlie   35         HR  50000.0
4     David   40         IT  60000.0

In [22]:
# Perform an inner join between df1 & df2 on id.
df1.join(df2,on="id",how="inner")

       name  age department  salary
id
3   Charlie   35         HR   50000
4     David   40         IT   60000