In [6]:
import pandas as pd

data = {
    "date": pd.date_range("2026-04-01", periods=10, freq="D"),
    "sales": [200, 220, 250, 270, 300, 280, 260, 310, 330, 350]
}

df = pd.DataFrame(data)
print(df)

        date  sales
0 2026-04-01    200
1 2026-04-02    220
2 2026-04-03    250
3 2026-04-04    270
4 2026-04-05    300
5 2026-04-06    280
6 2026-04-07    260
7 2026-04-08    310
8 2026-04-09    330
9 2026-04-10    350

# Datetime Conversion

In [7]:
# Convert the date column to datetime using pd.to_datetime()
df["date"]=pd.to_datetime(df["date"])
print(df)

        date  sales
0 2026-04-01    200
1 2026-04-02    220
2 2026-04-03    250
3 2026-04-04    270
4 2026-04-05    300
5 2026-04-06    280
6 2026-04-07    260
7 2026-04-08    310
8 2026-04-09    330
9 2026-04-10    350

In [8]:
# Extract year from the date column.
df["year"]=df["date"].dt.year
print(df)

        date  sales  year
0 2026-04-01    200  2026
1 2026-04-02    220  2026
2 2026-04-03    250  2026
3 2026-04-04    270  2026
4 2026-04-05    300  2026
5 2026-04-06    280  2026
6 2026-04-07    260  2026
7 2026-04-08    310  2026
8 2026-04-09    330  2026
9 2026-04-10    350  2026

In [9]:
# Extract month from the date column.
df["month"]=df["date"].dt.month
print(df)

        date  sales  year  month
0 2026-04-01    200  2026      4
1 2026-04-02    220  2026      4
2 2026-04-03    250  2026      4
3 2026-04-04    270  2026      4
4 2026-04-05    300  2026      4
5 2026-04-06    280  2026      4
6 2026-04-07    260  2026      4
7 2026-04-08    310  2026      4
8 2026-04-09    330  2026      4
9 2026-04-10    350  2026      4

In [10]:
df["day_of_week"]=df["date"].dt.day_name()
print(df)

        date  sales  year  month day_of_week
0 2026-04-01    200  2026      4   Wednesday
1 2026-04-02    220  2026      4    Thursday
2 2026-04-03    250  2026      4      Friday
3 2026-04-04    270  2026      4    Saturday
4 2026-04-05    300  2026      4      Sunday
5 2026-04-06    280  2026      4      Monday
6 2026-04-07    260  2026      4     Tuesday
7 2026-04-08    310  2026      4   Wednesday
8 2026-04-09    330  2026      4    Thursday
9 2026-04-10    350  2026      4      Friday

# Date Indexing

In [11]:
# Set date as the index of the DataFrame.
df=df.set_index("date")
print(df)

            sales  year  month day_of_week
date
2026-04-01    200  2026      4   Wednesday
2026-04-02    220  2026      4    Thursday
2026-04-03    250  2026      4      Friday
2026-04-04    270  2026      4    Saturday
2026-04-05    300  2026      4      Sunday
2026-04-06    280  2026      4      Monday
2026-04-07    260  2026      4     Tuesday
2026-04-08    310  2026      4   Wednesday
2026-04-09    330  2026      4    Thursday
2026-04-10    350  2026      4      Friday

In [12]:
# Select all rows between "2026-04-03" and "2026-04-07"
df.loc["2026-04-03":"2026-04-07"]

            sales  year  month day_of_week
date
2026-04-03    250  2026      4      Friday
2026-04-04    270  2026      4    Saturday
2026-04-05    300  2026      4      Sunday
2026-04-06    280  2026      4      Monday
2026-04-07    260  2026      4     Tuesday

In [13]:
# Select sales data for "2026-04-05" only.
df.loc["2026-04-05"]

sales             300
year             2026
month               4
day_of_week    Sunday
Name: 2026-04-05 00:00:00, dtype: object

# Resampling (Groups data into fixed buckets(weeks,months,etc))

In [50]:
import pandas as pd

# Create 30 days of sales data
data = {
    "date": pd.date_range("2026-04-01", periods=30, freq="D"),
    "sales": [200, 220, 250, 270, 300, 280, 260, 310, 330, 350,
              360, 370, 390, 400, 420, 410, 430, 440, 460, 470,
              480, 490, 500, 520, 530, 540, 550, 560, 570, 580]
}

df = pd.DataFrame(data)
df = df.set_index("date")   # set date as index for resampling
print(df.head())

            sales
date
2026-04-01    200
2026-04-02    220
2026-04-03    250
2026-04-04    270
2026-04-05    300

In [51]:
# Weekly totals
df.resample("W").sum()

            sales
date
2026-04-05   1240
2026-04-12   2260
2026-04-19   2950
2026-04-26   3530
2026-05-03   2260

In [52]:
# Monthly averages
df.resample("ME").mean()

            sales
date
2026-04-30  408.0

In [53]:
# Resample weekly but change the week ending day to Friday.
df.resample("W-FRI").sum()

            sales
date
2026-04-03    670
2026-04-10   2100
2026-04-17   2780
2026-04-24   3360
2026-05-01   3330

# Monthly Aggregation

In [54]:
# Resample monthly and calulate th average sales.
df.resample("ME").mean()

            sales
date
2026-04-30  408.0

In [55]:
# Resample monthly and find the maximum sales values.
df.resample("ME").max()

            sales
date
2026-04-30    580

In [56]:
# Resample monthly and count the number of records.
df.resample("ME").count()

            sales
date
2026-04-30     30

# Custom Intervals

In [57]:
# Resample every 3 days and calculate the sum.
df.resample("3D").sum()

            sales
date
2026-04-01    670
2026-04-04    850
2026-04-07    900
2026-04-10   1080
2026-04-13   1210
2026-04-16   1280
2026-04-19   1410
2026-04-22   1510
2026-04-25   1620
2026-04-28   1710

In [58]:
# Resample every 10 days and find the maximun.
df.resample("10D").max()

            sales
date
2026-04-01    350
2026-04-11    470
2026-04-21    580

# Comparing Aggregations

In [59]:
# Compare weekly sum vs mean side by side
weekly_sum=df.resample("W").sum()
weekly_mean=df.resample("W").mean()
sample=pd.concat([weekly_sum,weekly_mean],axis=1)
sample.columns=["Weekly Sum","Weekly Mean"]
print(sample)

            Weekly Sum  Weekly Mean
date
2026-04-05        1240   248.000000
2026-04-12        2260   322.857143
2026-04-19        2950   421.428571
2026-04-26        3530   504.285714
2026-05-03        2260   565.000000

In [60]:
# Compare monthly max vs min.
monthly_max=df.resample("ME").max()
monthly_min=df.resample("ME").min()
result=pd.concat([monthly_max,monthly_min],axis=1)
result.columns=["Monthly Max","Monthly Min"]
print(result)

            Monthly Max  Monthly Min
date
2026-04-30          580          200

# Advanced Twist

In [63]:
# Resample weekly and caculate the standard deviation of sales.
weekly_std=df.resample("W").std()
print(weekly_std)

                sales
date
2026-04-05  39.623226
2026-04-12  41.518785
2026-04-19  24.102954
2026-04-26  26.367368
2026-05-03  12.909944

In [ ]:
# Resample every 3 days and calculate the cumulative sum.
three_day_cumsum=df.resample("3D").sum().cumsum()
print(three_day_cumsum )

            sales
date
2026-04-01    670
2026-04-04   1520
2026-04-07   2420
2026-04-10   3500
2026-04-13   4710
2026-04-16   5990
2026-04-19   7400
2026-04-22   8910
2026-04-25  10530
2026-04-28  12240

In [68]:
# Resample monthly and calculate the median sales.
print(df.resample("ME").median())

            sales
date
2026-04-30  415.0

# Rolling (creates a moving window over data and applies functions inside that window)
  * General Syntax: df["sales"].rolling(window,min_periods=1).aggregation()

In [90]:
import pandas as pd
import numpy as np

# Generate 75 days (~2.5 months) of daily data
dates = pd.date_range("2026-03-01", periods=75, freq="D")

# Create some synthetic temperature values with variation
np.random.seed(42)  # reproducible
temps = np.random.randint(14, 30, size=75)  # temperatures between 14–29 °C

df = pd.DataFrame({"date": dates, "temperature": temps})
df = df.set_index("date")

print(df.head(10))

            temperature
date
2026-03-01           20
2026-03-02           17
2026-03-03           26
2026-03-04           28
2026-03-05           24
2026-03-06           21
2026-03-07           26
2026-03-08           18
2026-03-09           20
2026-03-10           23

In [92]:
# Compute a 7-day moving average of temperature.
result=df["temperature"].rolling(7).mean().to_frame("7D mean Temp")
print(result[5:18])

            7D mean Temp
date
2026-03-06           NaN
2026-03-07     23.142857
2026-03-08     22.857143
2026-03-09     23.285714
2026-03-10     22.857143
2026-03-11     21.142857
2026-03-12     20.571429
2026-03-13     21.000000
2026-03-14     20.714286
2026-03-15     21.142857
2026-03-16     20.857143
2026-03-17     20.000000
2026-03-18     20.714286

In [96]:
# Compare the 7-Day vs 14-Day moving averages side by side.
seven_day_avg=df["temperature"].rolling(7).mean()
fourteen_day_avg=df["temperature"].rolling(14).mean()
result=pd.concat([seven_day_avg,fourteen_day_avg],axis=1)
result.columns=["7 Day Mean Temp","14 Day Mean Temp"]
print(result.head(15))

            7 Day Mean Temp  14 Day Mean Temp
date
2026-03-01              NaN               NaN
2026-03-02              NaN               NaN
2026-03-03              NaN               NaN
2026-03-04              NaN               NaN
2026-03-05              NaN               NaN
2026-03-06              NaN               NaN
2026-03-07        23.142857               NaN
2026-03-08        22.857143               NaN
2026-03-09        23.285714               NaN
2026-03-10        22.857143               NaN
2026-03-11        21.142857               NaN
2026-03-12        20.571429               NaN
2026-03-13        21.000000               NaN
2026-03-14        20.714286         21.928571
2026-03-15        21.142857         22.000000

In [105]:
# Compare rolling sum with cumulative sum
sum=df["temperature"].rolling(10).sum()
cumsum=df["temperature"].rolling(10).sum().cumsum()
result=pd.concat([sum,cumsum],axis=1)
result.columns=["Sum","Cumsum"]
print(result[10:30])

              Sum  Cumsum
date
2026-03-11  219.0   442.0
2026-03-12  222.0   664.0
2026-03-13  220.0   884.0
2026-03-14  216.0  1100.0
2026-03-15  213.0  1313.0
2026-03-16  210.0  1523.0
2026-03-17  201.0  1724.0
2026-03-18  204.0  1928.0
2026-03-19  205.0  2133.0
2026-03-20  198.0  2331.0
2026-03-21  201.0  2532.0
2026-03-22  199.0  2731.0
2026-03-23  190.0  2921.0
2026-03-24  187.0  3108.0
2026-03-25  191.0  3299.0
2026-03-26  200.0  3499.0
2026-03-27  202.0  3701.0
2026-03-28  196.0  3897.0
2026-03-29  204.0  4101.0
2026-03-30  213.0  4314.0

In [106]:
# Find the maximum temperature in the last 5 days.
print(df["temperature"].rolling(5).max().to_frame("5D Rolling Max"))

            5D Rolling Max
date
2026-03-01             NaN
2026-03-02             NaN
2026-03-03             NaN
2026-03-04             NaN
2026-03-05            28.0
...                    ...
2026-05-10            27.0
2026-05-11            27.0
2026-05-12            27.0
2026-05-13            27.0
2026-05-14            23.0

[75 rows x 1 columns]

In [107]:
# Find the minimun temperature in the last 10 days.
print(df["temperature"].rolling(10).min().to_frame("10D Rolling Min"))

            10D Rolling Min
date
2026-03-01              NaN
2026-03-02              NaN
2026-03-03              NaN
2026-03-04              NaN
2026-03-05              NaN
...                     ...
2026-05-10             15.0
2026-05-11             15.0
2026-05-12             15.0
2026-05-13             15.0
2026-05-14             15.0

[75 rows x 1 columns]

In [110]:
# Compare rolling max vs rolling min
min=df["temperature"].rolling(2).min().to_frame("2D Rolling Min")
max=df["temperature"].rolling(2).max().to_frame("2D Rolling Max")
result=pd.concat([min,max],axis=1)
print(result.tail(12))

            2D Rolling Min  2D Rolling Max
date
2026-05-03            18.0            22.0
2026-05-04            20.0            22.0
2026-05-05            15.0            20.0
2026-05-06            15.0            17.0
2026-05-07            17.0            22.0
2026-05-08            22.0            25.0
2026-05-09            25.0            27.0
2026-05-10            15.0            27.0
2026-05-11            15.0            23.0
2026-05-12            22.0            23.0
2026-05-13            22.0            23.0
2026-05-14            18.0            23.0